#!/bin/bash
#---------------- Copyright notices and creator info-----------------------------#
#
# By Lopo Lencastre de Almeida Contact: [dev@ipublicis.com]
#
# Copyright 2014 iPublicis!COM
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#--------------------------------------------------------------------------------#

rootNisoChk() {
    if [ $(id -u) -eq 0 ]; then
       echo "Starting..."
       mktmp
       addrskel
       addopt
       addshare
       addthemes
       rmtmp
       echo "Done."
    else
       echo "Sorry, you are not root."
       exit 1
    fi
}

mktmp() {
  echo "Make TEMP dir"
  mkdir ~/TEMP > /dev/null
  cd ~/TEMP > /dev/null
}

rmtmp () {
  echo "Cleaning... "
  cd .. > /dev/null
  rm -rf ~/TEMP > /dev/null
}

addskel() {
  echo "Add skeleton files..."
  wget http://www.pinguyos.com/files/skel.zip  > /dev/null
  unzip -o skel.zip -d /etc/skel/  > /dev/null
  chmod -R a+rw /etc/skel  > /dev/null
  chmod -R 755 /etc/skel  > /dev/null
}

addopt() {
  echo "Add optional files..."
  wget http://www.pinguyos.com/files/opt.zip  > /dev/null
  unzip -o opt.zip -d /opt  > /dev/null
}

addshare() {
  echo "Add share files..."
  wget http://www.pinguyos.com/files/share.zip  > /dev/null
  unzip -o share.zip -d /usr/share  > /dev/null
}

addthemes() {
  echo "Add themes..."
  wget http://www.pinguyos.com/files/themes.zip  > /dev/null
  unzip -o themes.zip -d ./themes > /dev/null
  cd themes > /dev/null
  dpkg -i *.deb > /dev/null
  apt-get install -f > /dev/null
}

rootNisoChk
